### PR TITLE
eslint-plugin-react-hooks

### PR DESCRIPTION
**Pull request by chalkedgoose**
I am adding an eslint rule from the react team to make sure we are using hooks properly. This will break since it causes errors for the current linting system but once the issues at hand are addressed it should work fine and dandy again.

### CODE REVIEW

**Review by 4nkitd — APPROVED** [review]

**Comment by chalkedgoose** [comment]
@lucemans this will cause issues with the current linting tool but should be merged in since it will give
use real feedback on our hooks.

https://reactjs.org/docs/hooks-rules.html

**Comment by lucemans** [comment]
It appears it doesnt realize that `useAuth` is not a hook, rather a wrapper component...
Does it do this because `useAuth` matches the `use*` pattern of ur average hook? Do we rename it to `authorize`?

**Comment by chalkedgoose** [comment]
We'll need to follow up on this soon.

**Comment by chalkedgoose** [comment]
Going to reopen new branch

**Pull request closed without merging**
