### PR TITLE
Redux Persistence for Auth Token

### PR DESCRIPTION
**Pull request by chalkedgoose**
Redux Setup with Persistent Auth token store that is used everywhere in the react application.
Screen Shot 2021-06-02 at 7 50 52 PM
Also now we have neat dev tools

### CODE REVIEW

**Comment by lucemans** [comment]
Fix /assets aswell plz 👀

**Comment by chalkedgoose** [comment]
> Fix /assets aswell plz 👀

Assets are not modified in this commit.
I can fix them as a follow up.

**Review by lucemans — APPROVED** [review]
LGTM, not tested

**Review by 4nkitd — APPROVED** [review]
LGTM!

**Pull request merged**
